name: flutter_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_smart_retry: ^1.0.0
  encrypt: ^5.0.1
  equatable: ^2.0.3
  #  file_picker: ^5.2.3
  file: 6.1.4
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  go_router: ^4.2.7
  hive: ^2.2.3
  image_cropper: ^3.0.1
  image_picker: ^0.8.8
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  keyboard_dismisser: ^3.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  stream_transform: ^2.0.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/bitmap/
    - assets/images/flags/
    - assets/.env